var data = [
  {
    "previewImage": "https://www.bhg.com/thmb/3Vf9GXp3T-adDlU6tKpTbb-AEyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg",
    "title": "Cozy Apartment",
    "address": "123 Main St, Cityville",
    "city": "Cityville",
    "rent": 1500,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 100,
    "property_place": 101,
    "date_of_availability": "2023-08-15"
  },
  {
    "previewImage": "https://www.bhg.com/thmb/I277gk9XbxINQiJ8hGNqrKprOWU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/large-cape-cod-exterior-circular-driveway-0abc3587-ae293581d2384f9088652b6705c0ef56.jpg",
    "title": "Luxury Penthouse",
    "address": "101 Sky Tower, Metropolis",
    "city": "Metropolis",
    "rent": 4500,
    "bed": 4,
    "bath": 3,
    "dimension": 2200,
    "property_type": 1,
    "property_id": 101,
    "property_place": 102,
    "date_of_availability": "2023-08-30"
  },
  {
    "previewImage": "https://image.cnbcfm.com/api/v1/image/106758801-1603459526384-picture-perfect-beautiful-house-on-the-island-of-coronado-in-sunny-california-beautifully-landscaped_t20_6lJOrv.jpg?v=1603459593&w=1600&h=900",
    "title": "Charming Townhouse",
    "address": "789 Pine Dr, Suburbville",
    "city": "Suburbville",
    "rent": 1800,
    "bed": 2,
    "bath": 2,
    "dimension": 1100,
    "property_type": 1,
    "property_id": 102,
    "property_place": 103,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://res.akamaized.net/domain/image/fetch/t_web/c_fill,w_800,h_450/https://static.domain.com.au/domainblog/uploads/2017/03/03053000/1_guoycu.jpg",
    "title": "Lakeview Cottage",
    "address": "246 Lakeview Ln, Serenityville",
    "city": "Serenityville",
    "rent": 1200,
    "bed": 1,
    "bath": 1,
    "dimension": 700,
    "property_type": 1,
    "property_id": 103,
    "property_place": 104,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Mj6JL_wJrxkevZgilNDHfl87bukEJ3gnhfuj_TVCZmJxoA11TYinoI-Ji1dxxmPweGs&usqp=CAU",
    "title": "Spacious Heritage Home",
    "address": "789 Rose St, Heritageville",
    "city": "Heritageville",
    "rent": 2800,
    "bed": 4,
    "bath": 3,
    "dimension": 1800,
    "property_type": 1,
    "property_id": 104,
    "property_place": 105,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbozb2tPqhovy6oULYrIn2tzySQe4bgcMgsqymdipr78uxRBlBJVh_MfmQgovvuASqTdE&usqp=CAU",
    "title": "Country Estate",
    "address": "543 Oak Rd, Countryside",
    "city": "Countryside",
    "rent": 3500,
    "bed": 5,
    "bath": 4,
    "dimension": 3000,
    "property_type": 1,
    "property_id": 105,
    "property_place": 106,
    "date_of_availability": "2023-09-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxJP0oYqSrz87vbew52x2aRqII0a9_3INMddQjFVwk-Rft5RUeAZ-BbTo8qwIiQ49akG8&usqp=CAU",
    "title": "Modern Loft",
    "address": "654 Art Ave, Creativeland",
    "city": "Creativeland",
    "rent": 2000,
    "bed": 1,
    "bath": 1,
    "dimension": 1000,
    "property_type": 1,
    "property_id": 106,
    "property_place": 107,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTouSlAGWjbBKjx1MhTqfWQSkSf1GpKaxURGg&usqp=CAU",
    "title": "Sunny Bungalow",
    "address": "321 Garden Way, Greenburg",
    "city": "Greenburg",
    "rent": 1600,
    "bed": 2,
    "bath": 2,
    "dimension": 1200,
    "property_type": 1,
    "property_id": 107,
    "property_place": 108,
    "date_of_availability": "2023-07-01"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW69qywSY4YUu4aEIlGUIExbvqsIXBNDaumw&usqp=CAU",
    "title": "Riverside Retreat",
    "address": "987 Riverfront Rd, Waterside",
    "city": "Waterside",
    "rent": 2800,
    "bed": 3,
    "bath": 2,
    "dimension": 1500,
    "property_type": 1,
    "property_id": 108,
    "property_place": 109,
    "date_of_availability": "2023-08-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRBiN4AKHtJ9hDl-oXnLOZV2ZE2k-aC0sWkA&usqp=CAU",
    "title": "Studio Apartment",
    "address": "543 Metro Plaza, Cityscape",
    "city": "Cityscape",
    "rent": 1100,
    "bed": 1,
    "bath": 1,
    "dimension": 600,
    "property_type": 1,
    "property_id": 109,
    "property_place": 101,
    "date_of_availability": "2023-06-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2nxK-9HUwxZMVf9kJFSfVYZidzhXQshHkdw&usqp=CAU",
    "title": "Historic Brownstone",
    "address": "765 Brick St, Oldtown",
    "city": "Oldtown",
    "rent": 2400,
    "bed": 3,
    "bath": 2,
    "dimension": 1600,
    "property_type": 1,
    "property_id": 110,
    "property_place": 102,
    "date_of_availability": "2023-07-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSYy9kaLSCRK6sGAB7tWWyDosM8ajLzYZsKw&usqp=CAU",
    "title": "Lakefront Cabin",
    "address": "234 Lakeshore Dr, Tranquilville",
    "city": "Tranquilville",
    "rent": 1700,
    "bed": 2,
    "bath": 1,
    "dimension": 950,
    "property_type": 1,
    "property_id": 111,
    "property_place": 103,
    "date_of_availability": "2023-07-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCEiB04PGUpTFWxdNRIvq31D7wgjobBvZenw&usqp=CAU",
    "title": "Mountain View",
    "address": "876 Summit Rd, Scenic Hills",
    "city": "Scenic Hills",
    "rent": 1900,
    "bed": 3,
    "bath": 2,
    "dimension": 1400,
    "property_type": 1,
    "property_id": 112,
    "property_place": 104,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP7E-lRjOaRG7-3LFoXAhnSJgAeDZdYSIKGQ&usqp=CAU",
    "title": "Urban Condo",
    "address": "543 Metro Tower, Cityscape",
    "city": "Cityscape",
    "rent": 2200,
    "bed": 2,
    "bath": 2,
    "dimension": 1100,
    "property_type": 1,
    "property_id": 113,
    "property_place": 101,
    "date_of_availability": "2023-06-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz_Xy-p8iswEKMiURgiv-cLLhPUvATjyZqyA&usqp=CAU",
    "title": "Garden Oasis",
    "address": "765 Rose Garden Ln, Greenburg",
    "city": "Greenburg",
    "rent": 2000,
    "bed": 3,
    "bath": 2,
    "dimension": 1300,
    "property_type": 1,
    "property_id": 114,
    "property_place": 108,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9RhphoG8e3IbbVjElSKM7BFPZQOUZuBeHOg&usqp=CAU",
    "title": "Rural Retreat",
    "address": "543 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 1600,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 115,
    "property_place": 106,
    "date_of_availability": "2023-06-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXq5Et0Ffpir1HaDO8m7KNri5nYCHxWAyjmw&usqp=CAU",
    "title": "Downtown Studio",
    "address": "321 Downtown Ave, Cityville",
    "city": "Cityville",
    "rent": 1200,
    "bed": 1,
    "bath": 1,
    "dimension": 700,
    "property_type": 1,
    "property_id": 116,
    "property_place": 101,
    "date_of_availability": "2023-08-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfIm00RcKZEChWgpSyv-tXGbnUOOXZylbQ6g&usqp=CAU",
    "title": "Seaside Cottage",
    "address": "876 Ocean Breeze Ln, Waterside",
    "city": "Waterside",
    "rent": 1800,
    "bed": 2,
    "bath": 1,
    "dimension": 950,
    "property_type": 1,
    "property_id": 117,
    "property_place": 109,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfGlbMu1AyYU1dIN5XYnG9UBraBqymedg-iQ&usqp=CAU",
    "title": "Historic Manor",
    "address": "543 Estate Rd, Heritageville",
    "city": "Heritageville",
    "rent": 2400,
    "bed": 3,
    "bath": 2,
    "dimension": 1500,
    "property_type": 1,
    "property_id": 118,
    "property_place": 105,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNJzypWdnJ5UCoXQiXb-ONajRMtnItWjIe0A&usqp=CAU",
    "title": "Lakefront Paradise",
    "address": "123 Lakeside Dr, Tranquilville",
    "city": "Tranquilville",
    "rent": 1700,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 119,
    "property_place": 103,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjRtzZhckMTTtRvQ9e0qd807mDSu8Nr-xRTQ&usqp=CAU",
    "title": "Sunny Villa",
    "address": "654 Sun Blvd, Sunville",
    "city": "Sunville",
    "rent": 1800,
    "bed": 3,
    "bath": 2,
    "dimension": 1200,
    "property_type": 1,
    "property_id": 120,
    "property_place": 110,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGDOD15rVJ75v2czVTUMMszji8XxrkEjc1HQ&usqp=CAU",
    "title": "Countryside Retreat",
    "address": "321 Meadow View Rd, Countryside",
    "city": "Countryside",
    "rent": 1600,
    "bed": 2,
    "bath": 1,
    "dimension": 800,
    "property_type": 1,
    "property_id": 121,
    "property_place": 106,
    "date_of_availability": "2023-06-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR84pAHtPfU0RiHXGlxiePapBLLUi7cRTkJnw&usqp=CAU",
    "title": "Urban Condo",
    "address": "876 Metro Tower, Cityscape",
    "city": "Cityscape",
    "rent": 2000,
    "bed": 2,
    "bath": 2,
    "dimension": 1000,
    "property_type": 1,
    "property_id": 122,
    "property_place": 107,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZGOwT4vdpHBeaZoUUIKJ7YfnS80vjlZc6Ng&usqp=CAU",
    "title": "Garden Oasis",
    "address": "543 Rose Garden Ln, Greenburg",
    "city": "Greenburg",
    "rent": 2000,
    "bed": 3,
    "bath": 2,
    "dimension": 1300,
    "property_type": 1,
    "property_id": 123,
    "property_place": 108,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIZUfBwEULz9VpIHbx0wwJnKD5WpKmh-0MNw&usqp=CAU",
    "title": "Rural Getaway",
    "address": "321 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 1500,
    "bed": 2,
    "bath": 1,
    "dimension": 800,
    "property_type": 1,
    "property_id": 124,
    "property_place": 106,
    "date_of_availability": "2023-06-25"
  }
]




export default data;