var data = [
  {
    "previewImage": "https://www.bhg.com/thmb/3Vf9GXp3T-adDlU6tKpTbb-AEyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg",
    "title": "Cozy Apartment",
    "address": "123 Main St, Cityville",
    "city": "Cityville",
    "rent": 1500,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 100,
    "property_place": 101,
    "date_of_availability": "2023-08-15"
  },
  {
    "previewImage": "https://www.bhg.com/thmb/I277gk9XbxINQiJ8hGNqrKprOWU=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/large-cape-cod-exterior-circular-driveway-0abc3587-ae293581d2384f9088652b6705c0ef56.jpg",
    "title": "Luxury Penthouse",
    "address": "101 Sky Tower, Metropolis",
    "city": "Metropolis",
    "rent": 4500,
    "bed": 4,
    "bath": 3,
    "dimension": 2200,
    "property_type": 1,
    "property_id": 101,
    "property_place": 102,
    "date_of_availability": "2023-08-30"
  },
  {
    "previewImage": "https://image.cnbcfm.com/api/v1/image/106758801-1603459526384-picture-perfect-beautiful-house-on-the-island-of-coronado-in-sunny-california-beautifully-landscaped_t20_6lJOrv.jpg?v=1603459593&w=1600&h=900",
    "title": "Charming Townhouse",
    "address": "789 Pine Dr, Suburbville",
    "city": "Suburbville",
    "rent": 1800,
    "bed": 2,
    "bath": 2,
    "dimension": 1100,
    "property_type": 1,
    "property_id": 102,
    "property_place": 103,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://res.akamaized.net/domain/image/fetch/t_web/c_fill,w_800,h_450/https://static.domain.com.au/domainblog/uploads/2017/03/03053000/1_guoycu.jpg",
    "title": "Lakeview Cottage",
    "address": "246 Lakeview Ln, Serenityville",
    "city": "Serenityville",
    "rent": 1200,
    "bed": 1,
    "bath": 1,
    "dimension": 700,
    "property_type": 1,
    "property_id": 103,
    "property_place": 104,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9Mj6JL_wJrxkevZgilNDHfl87bukEJ3gnhfuj_TVCZmJxoA11TYinoI-Ji1dxxmPweGs&usqp=CAU",
    "title": "Spacious Heritage Home",
    "address": "789 Rose St, Heritageville",
    "city": "Heritageville",
    "rent": 2800,
    "bed": 4,
    "bath": 3,
    "dimension": 1800,
    "property_type": 1,
    "property_id": 104,
    "property_place": 105,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbozb2tPqhovy6oULYrIn2tzySQe4bgcMgsqymdipr78uxRBlBJVh_MfmQgovvuASqTdE&usqp=CAU",
    "title": "Country Estate",
    "address": "543 Oak Rd, Countryside",
    "city": "Countryside",
    "rent": 3500,
    "bed": 5,
    "bath": 4,
    "dimension": 3000,
    "property_type": 1,
    "property_id": 105,
    "property_place": 106,
    "date_of_availability": "2023-09-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxJP0oYqSrz87vbew52x2aRqII0a9_3INMddQjFVwk-Rft5RUeAZ-BbTo8qwIiQ49akG8&usqp=CAU",
    "title": "Modern Loft",
    "address": "654 Art Ave, Creativeland",
    "city": "Creativeland",
    "rent": 2000,
    "bed": 1,
    "bath": 1,
    "dimension": 1000,
    "property_type": 1,
    "property_id": 106,
    "property_place": 107,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTouSlAGWjbBKjx1MhTqfWQSkSf1GpKaxURGg&usqp=CAU",
    "title": "Sunny Bungalow",
    "address": "321 Garden Way, Greenburg",
    "city": "Greenburg",
    "rent": 1600,
    "bed": 2,
    "bath": 2,
    "dimension": 1200,
    "property_type": 1,
    "property_id": 107,
    "property_place": 108,
    "date_of_availability": "2023-07-01"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW69qywSY4YUu4aEIlGUIExbvqsIXBNDaumw&usqp=CAU",
    "title": "Riverside Retreat",
    "address": "987 Riverfront Rd, Waterside",
    "city": "Waterside",
    "rent": 2800,
    "bed": 3,
    "bath": 2,
    "dimension": 1500,
    "property_type": 1,
    "property_id": 108,
    "property_place": 109,
    "date_of_availability": "2023-08-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRBiN4AKHtJ9hDl-oXnLOZV2ZE2k-aC0sWkA&usqp=CAU",
    "title": "Studio Apartment",
    "address": "543 Metro Plaza, Cityscape",
    "city": "Cityscape",
    "rent": 1100,
    "bed": 1,
    "bath": 1,
    "dimension": 600,
    "property_type": 1,
    "property_id": 109,
    "property_place": 101,
    "date_of_availability": "2023-06-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2nxK-9HUwxZMVf9kJFSfVYZidzhXQshHkdw&usqp=CAU",
    "title": "Historic Brownstone",
    "address": "765 Brick St, Oldtown",
    "city": "Oldtown",
    "rent": 2400,
    "bed": 3,
    "bath": 2,
    "dimension": 1600,
    "property_type": 1,
    "property_id": 110,
    "property_place": 102,
    "date_of_availability": "2023-07-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSYy9kaLSCRK6sGAB7tWWyDosM8ajLzYZsKw&usqp=CAU",
    "title": "Lakefront Cabin",
    "address": "234 Lakeshore Dr, Tranquilville",
    "city": "Tranquilville",
    "rent": 1700,
    "bed": 2,
    "bath": 1,
    "dimension": 950,
    "property_type": 1,
    "property_id": 111,
    "property_place": 103,
    "date_of_availability": "2023-07-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCEiB04PGUpTFWxdNRIvq31D7wgjobBvZenw&usqp=CAU",
    "title": "Mountain View",
    "address": "876 Summit Rd, Scenic Hills",
    "city": "Scenic Hills",
    "rent": 1900,
    "bed": 3,
    "bath": 2,
    "dimension": 1400,
    "property_type": 1,
    "property_id": 112,
    "property_place": 104,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP7E-lRjOaRG7-3LFoXAhnSJgAeDZdYSIKGQ&usqp=CAU",
    "title": "Urban Condo",
    "address": "543 Metro Tower, Cityscape",
    "city": "Cityscape",
    "rent": 2200,
    "bed": 2,
    "bath": 2,
    "dimension": 1100,
    "property_type": 1,
    "property_id": 113,
    "property_place": 101,
    "date_of_availability": "2023-06-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz_Xy-p8iswEKMiURgiv-cLLhPUvATjyZqyA&usqp=CAU",
    "title": "Garden Oasis",
    "address": "765 Rose Garden Ln, Greenburg",
    "city": "Greenburg",
    "rent": 2000,
    "bed": 3,
    "bath": 2,
    "dimension": 1300,
    "property_type": 1,
    "property_id": 114,
    "property_place": 108,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9RhphoG8e3IbbVjElSKM7BFPZQOUZuBeHOg&usqp=CAU",
    "title": "Rural Retreat",
    "address": "543 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 1600,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 115,
    "property_place": 106,
    "date_of_availability": "2023-06-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXq5Et0Ffpir1HaDO8m7KNri5nYCHxWAyjmw&usqp=CAU",
    "title": "Downtown Studio",
    "address": "321 Downtown Ave, Cityville",
    "city": "Cityville",
    "rent": 1200,
    "bed": 1,
    "bath": 1,
    "dimension": 700,
    "property_type": 1,
    "property_id": 116,
    "property_place": 101,
    "date_of_availability": "2023-08-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfIm00RcKZEChWgpSyv-tXGbnUOOXZylbQ6g&usqp=CAU",
    "title": "Seaside Cottage",
    "address": "876 Ocean Breeze Ln, Waterside",
    "city": "Waterside",
    "rent": 1800,
    "bed": 2,
    "bath": 1,
    "dimension": 950,
    "property_type": 1,
    "property_id": 117,
    "property_place": 109,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfGlbMu1AyYU1dIN5XYnG9UBraBqymedg-iQ&usqp=CAU",
    "title": "Historic Manor",
    "address": "543 Estate Rd, Heritageville",
    "city": "Heritageville",
    "rent": 2400,
    "bed": 3,
    "bath": 2,
    "dimension": 1500,
    "property_type": 1,
    "property_id": 118,
    "property_place": 105,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNJzypWdnJ5UCoXQiXb-ONajRMtnItWjIe0A&usqp=CAU",
    "title": "Lakefront Paradise",
    "address": "123 Lakeside Dr, Tranquilville",
    "city": "Tranquilville",
    "rent": 1700,
    "bed": 2,
    "bath": 1,
    "dimension": 900,
    "property_type": 1,
    "property_id": 119,
    "property_place": 103,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjRtzZhckMTTtRvQ9e0qd807mDSu8Nr-xRTQ&usqp=CAU",
    "title": "Sunny Villa",
    "address": "654 Sun Blvd, Sunville",
    "city": "Sunville",
    "rent": 1800,
    "bed": 3,
    "bath": 2,
    "dimension": 1200,
    "property_type": 1,
    "property_id": 120,
    "property_place": 110,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGDOD15rVJ75v2czVTUMMszji8XxrkEjc1HQ&usqp=CAU",
    "title": "Countryside Retreat",
    "address": "321 Meadow View Rd, Countryside",
    "city": "Countryside",
    "rent": 1600,
    "bed": 2,
    "bath": 1,
    "dimension": 800,
    "property_type": 1,
    "property_id": 121,
    "property_place": 106,
    "date_of_availability": "2023-06-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR84pAHtPfU0RiHXGlxiePapBLLUi7cRTkJnw&usqp=CAU",
    "title": "Urban Condo",
    "address": "876 Metro Tower, Cityscape",
    "city": "Cityscape",
    "rent": 2000,
    "bed": 2,
    "bath": 2,
    "dimension": 1000,
    "property_type": 1,
    "property_id": 122,
    "property_place": 107,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZGOwT4vdpHBeaZoUUIKJ7YfnS80vjlZc6Ng&usqp=CAU",
    "title": "Garden Oasis",
    "address": "543 Rose Garden Ln, Greenburg",
    "city": "Greenburg",
    "rent": 2000,
    "bed": 3,
    "bath": 2,
    "dimension": 1300,
    "property_type": 1,
    "property_id": 123,
    "property_place": 108,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIZUfBwEULz9VpIHbx0wwJnKD5WpKmh-0MNw&usqp=CAU",
    "title": "Rural Getaway",
    "address": "321 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 1500,
    "bed": 2,
    "bath": 1,
    "dimension": 800,
    "property_type": 1,
    "property_id": 124,
    "property_place": 106,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNAvycjV3z7OTGJaYUYqraFl16pEvrjCZkMl_wIzIsAbcb45NL0vg6exgur2kDXGcuScc&usqp=CAU",
    "title": "Scenic Hilltop Land",
    "address": "123 Summit Rd, Scenic Hills",
    "city": "Scenic Hills",
    "rent": 50000,
    "dimension": 10000,
    "property_type": 2,
    "property_id": 1001,
    "property_place": 104,
    "date_of_availability": "2023-08-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpI-oYqkd9csHMKqm-WUJJLUN_5xW85tvVy8r4I29gjEMyqow1lfPw5eVlnRNE1UBGWsg&usqp=CAU",
    "title": "Waterfront Land",
    "address": "101 Lakeside Dr, Tranquilville",
    "city": "Tranquilville",
    "rent": 75000,
    "dimension": 15000,
    "property_type": 2,
    "property_id": 1002,
    "property_place": 103,
    "date_of_availability": "2023-08-30"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp5jAw01VlqQJ1xN6yLLqF57j9_4VOCZBUzRpf33bKFyZIMJpUybiwoqbZavl_zV19IYk&usqp=CAU",
    "title": "Suburban Lot",
    "address": "789 Meadow Ave, Suburbville",
    "city": "Suburbville",
    "rent": 40000,
    "dimension": 8000,
    "property_type": 2,
    "property_id": 1003,
    "property_place": 103,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLKUDwi2pleI4w4z7e3bPISmrNoiKjGdTSnwTRahq0lGHfBfZfg1KhyJJOeV9wATLZkbE&usqp=CAU",
    "title": "Secluded Forest Land",
    "address": "246 Pine Rd, Serenityville",
    "city": "Serenityville",
    "rent": 60000,
    "dimension": 12000,
    "property_type": 2,
    "property_id": 1004,
    "property_place": 104,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCAymlgHdrvKbDwh-7F9PcRbFlGLD8RdSiY1tBZFD0UHswIe4P960t-PJ7R_D33SWQSgE&usqp=CAU",
    "title": "Cityscape Plot",
    "address": "789 Urban St, Cityscape",
    "city": "Cityscape",
    "rent": 90000,
    "dimension": 18000,
    "property_type": 2,
    "property_id": 1005,
    "property_place": 101,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbpA_cK1fbOXt-0ejL5sllJa5tmqRmiPzvIf-XA203sn8RLLBKVHdFWu2hr4isKhmJLR4&usqp=CAU",
    "title": "Countryside Acreage",
    "address": "543 Country Rd, Countryside",
    "city": "Countryside",
    "rent": 80000,
    "dimension": 16000,
    "property_type": 2,
    "property_id": 1006,
    "property_place": 106,
    "date_of_availability": "2023-09-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi7bR5fTxDVmXAtvaaObTqEHnqG8G37HrxgYKZrcd-ZIjH9w6TFfaUX_kktIMnccl_yEY&usqp=CAU",
    "title": "Riverside Parcel",
    "address": "654 Riverbank Ln, Waterside",
    "city": "Waterside",
    "rent": 65000,
    "dimension": 13000,
    "property_type": 2,
    "property_id": 1007,
    "property_place": 109,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLKUDwi2pleI4w4z7e3bPISmrNoiKjGdTSnwTRahq0lGHfBfZfg1KhyJJOeV9wATLZkbE&usqp=CAU",
    "title": "Mountain View Land",
    "address": "321 Summit View Rd, Scenic Hills",
    "city": "Scenic Hills",
    "rent": 55000,
    "dimension": 11000,
    "property_type": 2,
    "property_id": 1008,
    "property_place": 104,
    "date_of_availability": "2023-07-01"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmlgDDIWfzJuF3sm-TPW5Ni3_ACjrUraVfN1Qh4_2YjeqouEifRABYVdvp3NzzlFsG5Dw&usqp=CAU",
    "title": "Rural Countryside Plot",
    "address": "987 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 70000,
    "dimension": 14000,
    "property_type": 2,
    "property_id": 1009,
    "property_place": 106,
    "date_of_availability": "2023-08-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8PEhUlz-TboWXggjwyk7xQ8LpAgA176En1Ed9e1gVsq9VnSs9XJopAXnMghdNrNn2d3M&usqp=CAU",
    "title": "Seaside Lot",
    "address": "543 Ocean View Rd, Waterside",
    "city": "Waterside",
    "rent": 80000,
    "dimension": 16000,
    "property_type": 2,
    "property_id": 1010,
    "property_place": 109,
    "date_of_availability": "2023-06-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp5jAw01VlqQJ1xN6yLLqF57j9_4VOCZBUzRpf33bKFyZIMJpUybiwoqbZavl_zV19IYk&usqp=CAU",
    "title": "Urban Development Site",
    "address": "765 Downtown Plaza, Cityscape",
    "city": "Cityscape",
    "rent": 120000,
    "dimension": 24000,
    "property_type": 2,
    "property_id": 1011,
    "property_place": 101,
    "date_of_availability": "2023-07-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZYZJZuNK_FhjhcsSZuhZR1U1ZN8pKn0YhgLt9dSPVHR7e7uEER-Rzzvn_lCIR9pNqGg&usqp=CAU",
    "title": "Countryside Acre",
    "address": "234 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 75000,
    "dimension": 15000,
    "property_type": 2,
    "property_id": 1012,
    "property_place": 106,
    "date_of_availability": "2023-07-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLQvxJh2hHwMAECuw0MCtQi05qWqUUhdPB-fogkz6RiHR1q-zf2y_sYNFImC6uNCEk4DU&usqp=CAU",
    "title": "Mountain Retreat",
    "address": "876 Mountain View Ln, Scenic Hills",
    "city": "Scenic Hills",
    "rent": 60000,
    "dimension": 12000,
    "property_type": 2,
    "property_id": 1013,
    "property_place": 104,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ20u_AC3r6rw-O5fE3EpuuaaiD8L6dyjzk61iLPw7LcJwIaMHlFNes7EqUL2KiVKMq-LU&usqp=CAU",
    "title": "Urban Commercial Plot",
    "address": "543 Downtown Ave, Cityscape",
    "city": "Cityscape",
    "rent": 150000,
    "dimension": 30000,
    "property_type": 2,
    "property_id": 1014,
    "property_place": 101,
    "date_of_availability": "2023-06-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx-J7-xepdV8X2n64WX_Qq4xXQOgpPMDZe3Cl5bPOUK_uq7auWi7ILpZPmVJ12BHsspLo&usqp=CAU",
    "title": "Greenbelt Land",
    "address": "765 Greenbelt Rd, Greenburg",
    "city": "Greenburg",
    "rent": 70000,
    "dimension": 14000,
    "property_type": 2,
    "property_id": 1015,
    "property_place": 108,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMuTlrZsgRD5E1p3HMapfXoBm-NN0tbpiFC2SXUGJOtJF7hiIdHrgpyZQ07CsHb8dia9o&usqp=CAU",
    "title": "Rural Homestead",
    "address": "543 Farm Rd, Countryside",
    "city": "Countryside",
    "rent": 80000,
    "dimension": 16000,
    "property_type": 2,
    "property_id": 1016,
    "property_place": 106,
    "date_of_availability": "2023-06-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHv3mhrrRxQS9L-jttmuMAYdWT115EgZ6IfJM93tiEz5UV2r4s2UHqrEDtLVJhW3m4cQQ&usqp=CAU",
    "title": "Downtown Commercial Land",
    "address": "321 Business Blvd, Cityville",
    "city": "Cityville",
    "rent": 180000,
    "dimension": 36000,
    "property_type": 2,
    "property_id": 1017,
    "property_place": 101,
    "date_of_availability": "2023-08-05"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZATpaF-s_B569Cmh0njq4hMjaSsiqhQJY0DizucFZVzzImsMuW0on-FvIlz2I3q1C0II&usqp=CAU",
    "title": "Waterfront Property",
    "address": "876 Oceanfront Dr, Waterside",
    "city": "Waterside",
    "rent": 95000,
    "dimension": 19000,
    "property_type": 2,
    "property_id": 1018,
    "property_place": 109,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdgZJE30v7OANl8zzZ5IRc9QI4rhkkPev84KB4nTJNB4ft6X8jcWRdj4Y02bRZfX4EW4U&usqp=CAU",
    "title": "Heritage District Lot",
    "address": "543 Historic Ln, Heritageville",
    "city": "Heritageville",
    "rent": 80000,
    "dimension": 16000,
    "property_type": 2,
    "property_id": 1019,
    "property_place": 105,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS73OeAGOYRhh_CSXtjF0mfYXMJ7XJt24hwfkkVtroY4UCWYHQhOcYPn5POMeg1vIsWtTA&usqp=CAU",
    "title": "Coastal Land",
    "address": "123 Coastal Rd, Tranquilville",
    "city": "Tranquilville",
    "rent": 90000,
    "dimension": 18000,
    "property_type": 2,
    "property_id": 1020,
    "property_place": 103,
    "date_of_availability": "2023-06-25"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyaaHK28dNu9q42qXTb81897dPv-7AyRl7Tw&usqp=CAU",
    "title": "Sunville Plot",
    "address": "654 Sun Ave, Sunville",
    "city": "Sunville",
    "rent": 70000,
    "dimension": 14000,
    "property_type": 2,
    "property_id": 1021,
    "property_place": 110,
    "date_of_availability": "2023-07-15"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQnj4nBykR0M8iBpKNk1absDUK4u7ula8VJmvEGznNmNVqbnyyOCXOL93DV5WNnSt1r2I&usqp=CAU",
    "title": "Countryside Retreat",
    "address": "321 Meadow View Rd, Countryside",
    "city": "Countryside",
    "rent": 60000,
    "dimension": 12000,
    "property_type": 2,
    "property_id": 1022,
    "property_place": 106,
    "date_of_availability": "2023-06-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1uhMEyb4_W64UOZQFwA7xvYCqYNv43VLLal4E9UTHqZKGZePd43lHG1XNjLg6QW1_USk&usqp=CAU",
    "title": "Urban Land Parcel",
    "address": "876 Metro Blvd, Cityscape",
    "city": "Cityscape",
    "rent": 120000,
    "dimension": 24000,
    "property_type": 2,
    "property_id": 1023,
    "property_place": 107,
    "date_of_availability": "2023-07-20"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJSHy7UUqtTAKdjbLUwklpTn_PjZfvBxJVp3Dr7Hm3EJC06OM5_POeG9nEwVeINN-45kI&usqp=CAU",
    "title": "Greenburg Plot",
    "address": "543 Greenbelt Ave, Greenburg",
    "city": "Greenburg",
    "rent": 75000,
    "dimension": 15000,
    "property_type": 2,
    "property_id": 1024,
    "property_place": 108,
    "date_of_availability": "2023-08-10"
  },
  {
    "previewImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBpbTlIVInPE5f_KbVDvA239X0v8R66a60Zc964UKgRRignn1ShJYsu03osiPZO9Rw0-w&usqp=CAU",
    "title": "Rural Acreage",
    "address": "321 Meadow Rd, Countryside",
    "city": "Countryside",
    "rent": 65000,
    "dimension": 13000,
    "property_type": 2,
    "property_id": 1025,
    "property_place": 106,
    "date_of_availability": "2023-06-25"
  }
]




export default data;